spring:
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    org.springframework.security: DEBUG
    org:
      hibernate:
        type: trace
